version: 2.1

defaults: &defaults
  environment:
    CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>...<<pipeline.git.revision>>
  working_directory: ~/app

executors:
  node:
    <<: *defaults
    docker:
      - image: circleci/node:lts

commands:
  build_package:
    description: "build a single package"
    parameters:
      pkg:
        type: string
    steps:
      - run:
          name: "Build << parameters.pkg >>"
          command: |
            yarn workspace << parameters.pkg >> build
  should_build:
    description: "command that halt it should not build this package"
    parameters:
      pkg:
        type: string
    steps:
      - run:
          name: "Should Build << parameters.pkg >>"
          command: |
            SHOULD_BUILD=$(yarn entria-deploy hasChanged $CIRCLECI_COMPARE_URL << parameters.pkg >>)
            echo $SHOULD_BUILD
            if [ "$SHOULD_BUILD" == false ]; then
                circleci-agent step halt
            fi

jobs:
  install_deps:
    executor: node
    steps:
      - checkout
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Yarn install"
          command: |
            yarn install --frozen-lockfile --production=false --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
            - ./packages/babel/node_modules
            - ./packages/deploy/node_modules
            - ./packages/packageA/node_modules
            - ./packages/packageB/node_modules
            - ./packages/packageC/node_modules
            - ./packages/packageD/node_modules
      - persist_to_workspace:
          root: .
          paths: .
  tests:
    executor: node
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: "Run only needed tests"
          command: |
            TESTFILES=$(yarn entria-deploy changes $CIRCLECI_COMPARE_URL)
            echo $TESTFILES
            jest --forceExit --ci --maxWorkers=4 --findRelatedTests $TESTFILES

  conditional_build_package:
    description: "conditional build a package"
    parameters:
      pkg:
        type: string
    executor: node
    steps:
      - attach_workspace:
            at: ~/app
      - should_build:
          pkg: << parameters.pkg >>
      - build_package:
          pkg: << parameters.pkg >>

workflows:
  version: 2
  full:
    jobs:
      - install_deps
      - test:
          requires:
            - install_deps
      - conditional_build_package:
          path: "packages/packageA"
          requires:
            - test
      - conditional_build_package:
          path: "packages/packageB"
          requires:
            - test
      - conditional_build_package:
          path: "packages/packageC"
          requires:
            - test
      - conditional_build_package:
          path: "packages/packageD"
          requires:
            - test
